utags.ko: solve the unused remove_proc_subtree symbol Defenderinition
fix the compile error during GKI kernel 5.4:
ERROR: "remove_proc_subtree" [../../motorola/kernel/modules/drivers/misc/utag/utags.ko] unDefenderined!

Change-Id: I861abd86c558b8b8fc46f77794d83e66d27b1bf5
Reviewed-on: https://gerrit.mot.com/1706098
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key