Awinic: fix build error due to wakeup_source API's
Fix below build error
"aw8697.c:4182:48: error: too few arguments to function call, expected 2"

Change-Id: Ie5cf32d2ce27f661228f59352370793b79064100