utags: fix build error on kernel 5.15
SM8550 product use kernel 5.15, and utags driver build errors:
1.BIO_MAX_PAGES has been rename to BIO_MAX_VECS
.../drivers/misc/utag/utags.c:171:41: error: use of undeclared identifier 'BIO_MAX_PAGES'
                   num = (left_pages >= BIO_MAX_PAGES) ? BIO_MAX_PAGES : left_pages;

2. get_fs and set_fs() are not exported from 5.15
drivers/misc/utag/utags.c:1268:7: error: implicit declaration of function 'get_fs' [-Werror,-Wim
           fs = get_fs();

3. uselss fp variable that is not used

Change-Id: Ia031b5042124a608cdcf956795bd2e0bd6844689
Reviewed-on: https://gerrit.mot.com/2237918
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Guobin Zhang <zhanggb@motorola.com>
Submit-Approved: Jira Key
Reviewed-on: https://gerrit.mot.com/2781997
Reviewed-by: Huosheng Liao <liaohs@motorola.com>