Fix build error unused-but-set-variable in sr100
motorola/kernel/modules/drivers/uwb/sr100/sr100.c:656:7: error: variable
'retry_count' set but not used [-Werror,-Wunused-but-set-variable]
  int retry_count = 0;

Change-Id: Ied2b704e11f5ded4ca8125ad0176573f3aefc6d0
Signed-off-by: Srihari Sathyanarayana <sriharis@motorola.com>
Reviewed-on: https://gerrit.mot.com/2465217
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Qing Chang <qing@motorola.com>
Tested-by: Jira Key
Submit-Approved: Jira Key