Resolve compilation errors with unused parameters
TP:
fts.c:4035:14: warning: unused variable 'supplier' [-Wunused-variable]

Change-Id: Idd9030aa7a51f9f9da142481436f1e4c3b95e200
Reviewed-on: https://gerrit.mot.com/1925632
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Wei Deng <dengwei1@motorola.com>
Reviewed-by: Jichao Zou <zoujc@motorola.com>
Submit-Approved: Jira Key