moto_swap: add backend_zstd to moto_swap
After update to the latest GKI (android16-6.12-2025-09_r15), symbols are
missing in the built code, causing build failures. This change address
this failure.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: modpost: "backend_zstd" [../motorola/kernel/modules/drivers/moto_swap/moto_swap.ko] undefined!
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Change-Id: I6f75a3c161823c9c22426549bdaf59d75d22f9a1
Reviewed-on: https://gerrit.mot.com/3659827
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Xinmin Fu <fuxm1@motorola.com>
Submit-Approved: Gilberto Gambugge Neto <gambugge@motorola.com>