utag: fix build error for kernel6.18
error:
/home/qianlong2/src/8975/moto_mainline_init_0323/kernel_platform/out/bazel/output_user_root/60fbafb12df6a9ad415dee434bb4eb42/sandbox/linux-sandbox/219/execroot/_main/motorola/kernel/modules/drivers/misc/utag/utags.c:2265:18: error: expected ';' after top level declarator
 2265 | MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);

Starting from Linux kernel 6.13, the MODULE_IMPORT_NS macro requires its argument
to be a string literal (enclosed in double quotes). The kernel mainline removed the
internal stringification from the macro definition to simplify the underlying symbol
namespace implementation and improve parsing by module tools l(CR) modpost.

Change-Id: Ie80f5efe1a57c25a57f14ead17d94dc49e8afdba
Signed-off-by: qianlong <qianl2@motorola.com>
Reviewed-on: https://gerrit.mot.com/3839757
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Obi-Wan Kenobi
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key