Revert "(CR) Sensors:add capsense sx933x usb and headset calibrate"
This reverts commit f1f464c061c8d1da51017f76a5ae8b5d5b9468fc.

  CC [M]  ../../motorola/kernel/modules/drivers/misc/sx933x/sx933x_sar.o
  /localrepo/a22472/5g/kernel/msm-4.14/../../motorola/kernel/modules/drivers/misc/sx933x/sx933x_sar.c:410:2: error: unknown field 'class_attrs' specified in initializer
  .class_attrs  = capsense_class_attributes,
  ^

Change-Id: I3795dddd352884c037fb02c50613511a3281b74b
Reviewed-on: https://gerrit.mot.com/1229396
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Yin-Jun Chen <a7301c@motorola.com>
Submit-Approved: Jira Key