nova_0flash_mmi: fix build failure
Fix 'undefined symbol' build failure at kernel 5.4:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: "mmi_device_is_available" [../../motorola/kernel/modules/drivers/
       input/touchscreen/nova_0flash_mmi/nova_0flash_mmi.ko] undefined! 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Change-Id: I4ab25a9b25e2a852951a72bd82a6f1531d1fa6a2
Reviewed-on: https://gerrit.mot.com/2517947
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Rafael Ortolan <rafones@motorola.com>
Tested-by: Jira Key
Reviewed-by: Marcelo Pincinato <mpcinato@motorola.com>
Submit-Approved: Marcelo Pincinato <mpcinato@motorola.com>
(cherry picked from commit c6e8afc83b980764830d257a680666a975ea5647)
Reviewed-on: https://gerrit.mot.com/2556936