Revert "(CR) synaptics_mmi_class: fix build issue"
This reverts commit 0b6bf1eff7be148a3a374f2897658ad683691d35.

  This change broke main line and Q2 builds for products cebu, guamp, guam, borneo, astro, olson, denver
   
   Error: motorola/kernel/modules/drivers/input/touchscreen/synaptics_mmi_class: MODULE.TARGET.DLKM.synaptics_dsx_fw_update.ko already defined by motorola/kernel/modules/drivers/input/touchscreen/synaptics_mm

Change-Id: Ia9c9bab956a8a5fbb740e9890316620c55b9d635
Reviewed-on: https://gerrit.mot.com/1913587
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Marcelo Pincinato <mpcinato@motorola.com>
Submit-Approved: Marcelo Pincinato <mpcinato@motorola.com>
Tested-by: Marcelo Pincinato <mpcinato@motorola.com>