fix utags module can not pass build on MTK kernel6.6
Reason:
utags module fails to build due to below errors:
motorola/kernel/modules/drivers/misc/utag/utags.c:481:14: error: call to undeclared function 'bdev_file_open_by_path'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  481 |         bdev_file = bdev_file_open_by_path(cb->name, FMODE_READ | FMODE_WRITE, cb, NULL);
motorola/kernel/modules/drivers/misc/utag/utags.c:482:9: error: call to undeclared function 'file_bdev'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  482 |         bdev = file_bdev(bdev_file);
motorola/kernel/modules/drivers/misc/utag/utags.c:2285:3: error: call to undeclared function 'bdev_fput'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2285 |                 bdev_fput(ctrl->main.filep);

Solution:
Add proper kernel version marco check for those symbols only available
on kernel6.12

Test:
passed build

Change-Id: Ia00fbedb6974a6c4035fad73d2c73fe622cc54cb
Reviewed-on: https://gerrit.mot.com/3557494
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Pdo Scm <hudsoncm@motorola.com>
Reviewed-by: Wenqiang Han <hanwq2@motorola.com>
Reviewed-by: Xiangpo Zhao <zhaoxp3@motorola.com>
Submit-Approved: Jira Key