Power: fix implicit bld errs of wakeup_source API's
fix implicit bld errs of wakeup_source API's in Android R

On latest kernel rebase from QC:

we see couple of wakeup_source API's are removed,

errors as below:

motorola/kernel/modules/drivers/power/qpnp-smbcharger-mmi/qpnp-smbcharger-mmi.c:4120:2: error: implicit declaration of function 'wakeup_source_init' [-Werror,-Wimplicit-function-declaration]
motorola/kernel/modules/drivers/power/qpnp-smbcharger-mmi/qpnp-smbcharger-mmi.c:4443:2: error: implicit declaration of function 'wakeup_source_trash' [-Werror,-Wimplicit-function-declaration]

motorola/kernel/modules/drivers/power/p938x_charger/p938x_charger.c:2945:2: error: implicit declaration of function 'wakeup_source_init' [-Werror,-Wimplicit-function-declaration]
        wakeup_source_init(&chip->wls_wake_source, "p938x wireless charger");
motorola/kernel/modules/drivers/power/p938x_charger/p938x_charger.c:3015:2: error: implicit declaration of function 'wakeup_source_trash' [-Werror,-Wimplicit-function-declaration]
        wakeup_source_trash(&chip->wls_wake_source);

This fix replaces

1) wakeup_source_init(..) function with to wakeup_source_register(..)
2) wakeup_source_trash(..) function with to wakeup_source_unregister(..)

Change-Id: I9639f64ad8f9efeaf8f3d199f9a2af27341b145b
Signed-off-by: kumarv <kumarv@motorola.com>